import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";
import "./globals.css";
import WrapperLayout from "@/widgets/layout/WrapperLayout";

const golos = Golos_Text({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={golos.className}>
        <WrapperLayout>{children}</WrapperLayout>
      </body>
    </html>
  );
}
